test

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -1,3 +1,10 @@
+##
+## EPITECH PROJECT, 2023
+## DEVOPS
+## File description:
+## integration.yml
+##
+
 name: continous-integration
 
 on:
@@ -9,6 +16,31 @@ on:
 jobs:
 
     coding-style:
+        name: Run Banana
+        runs-on: ubuntu-latest
+        container:
+            image: ghcr.io/epitech/
+            coding-style-checker: latest
+
+        steps:
+
+            - name: Checkout GH repo
+              uses: actions/checkout@master
+
+            - name: Run coding-style-checker
+              run: check.sh $(pwd) $(pwd)
+
+            - name: Report banana result
+              run: |
+                NB_ERROR=$(cat coding-style-reports.log |
+                wc -l)
+                if [ $NB_ERROR -gt 0 ]; then
+                    ERROR=$(cat coding-style-reports.log)
+                    echo "::error title=$NB_ERROR errors
+                    found::$ERROR"
+                    exit 1
+                fi
+                exit 0
 
     compile:
         runs-on: ubuntu-latest
